### ISSUE TITLE
应用安装完成后第一次打开闪退【已解决】

### ISSUE THREAD

**Issue by otakumr** [CapitalGrin/AzurLaneBiliBili-Perseus#6]
安装包安装完打开闪退，然后出现用户协议，点击确定就没有然后了，是哪里需要设置一下吗

**Comment by Harmskyblue** [comment]
如果是模拟器，我测试下来只有逍遥模拟器反复打开几次可以进入，雷电，mumu等模拟器都会反复闪退

> 安装包安装完打开闪退，然后出现用户协议，点击确定就没有然后了，是哪里需要设置一下吗

**Comment by CapitalGrin** [comment]
解决闪退问请转向使用 https://github.com/JMBQ/azurlane/releases/tag/1.0 ，注意配置文件名，感谢Rem。

**Comment by otakumr** [comment]
> 如果是模拟器，我测试下来只有逍遥模拟器反复打开几次可以进入，雷电，mumu等模拟器都会反复闪退
> 
> > 安装包安装完打开闪退，然后出现用户协议，点击确定就没有然后了，是哪里需要设置一下吗

我是试了只能蓝叠模拟器，其他的都闪退。顺带问一下，你全皮服客户端能和魔改皮肤一起用吗，我两个一起用会闪退

**Comment by Harmskyblue** [comment]
> > 如果是模拟器，我测试下来只有逍遥模拟器反复打开几次可以进入，雷电，mumu等模拟器都会反复闪退
> > > 安装包安装完打开闪退，然后出现用户协议，点击确定就没有然后了，是哪里需要设置一下吗
> 
> 我是试了只能蓝叠模拟器，其他的都闪退。顺带问一下，你全皮服客户端能和魔改皮肤一起用吗，我两个一起用会闪退

魔改是因为有部分皮肤文件失效，加载到这些皮肤的时候会崩溃，我用的五月份的魔改，在船坞里找到荒潮和满朝这两艘船时就会闪退，我把这两个的皮肤原文件替换回来后就正常了，现在的不清楚

**Comment by otakumr** [comment]
> > > 如果是模拟器，我测试下来只有逍遥模拟器反复打开几次可以进入，雷电，mumu等模拟器都会反复闪退
> > > > 安装包安装完打开闪退，然后出现用户协议，点击确定就没有然后了，是哪里需要设置一下吗
> > 
> > 
> > 我是试了只能蓝叠模拟器，其他的都闪退。顺带问一下，你全皮服客户端能和魔改皮肤一起用吗，我两个一起用会闪退
> 
> 魔改是因为有部分皮肤文件失效，加载到这些皮肤的时候会崩溃，我用的五月份的魔改，在船坞里找到荒潮和满朝这两艘船时就会闪退，我把这两个的皮肤原文件替换回来后就正常了，现在的不清楚

你五月份的魔改包出处还记得在哪里吗，可以分享一下嘛，当然如果找不到了也没关系。

**Comment by Harmskyblue** [comment]
> > > > 如果是模拟器，我测试下来只有逍遥模拟器反复打开几次可以进入，雷电，mumu等模拟器都会反复闪退
> > > > > 安装包安装完打开闪退，然后出现用户协议，点击确定就没有然后了，是哪里需要设置一下吗
> > > 
> > > 
> > > 我是试了只能蓝叠模拟器，其他的都闪退。顺带问一下，你全皮服客户端能和魔改皮肤一起用吗，我两个一起用会闪退
> > 
> > 
> > 魔改是因为有部分皮肤文件失效，加载到这些皮肤的时候会崩溃，我用的五月份的魔改，在船坞里找到荒潮和满朝这两艘船时就会闪退，我把这两个的皮肤原文件替换回来后就正常了，现在的不清楚
> 
> 你五月份的魔改包出处还记得在哪里吗，可以分享一下嘛，当然如果找不到了也没关系。

https://laowang.vip/home.php?mod=space&uid=1247954&do=thread&view=me&from=space
这个作者一直在整理

**Comment by otakumr** [comment]
> > > > > 如果是模拟器，我测试下来只有逍遥模拟器反复打开几次可以进入，雷电，mumu等模拟器都会反复闪退
> > > > > > 安装包安装完打开闪退，然后出现用户协议，点击确定就没有然后了，是哪里需要设置一下吗
> > > > 
> > > > 
> > > > 我是试了只能蓝叠模拟器，其他的都闪退。顺带问一下，你全皮服客户端能和魔改皮肤一起用吗，我两个一起用会闪退
> > > 
> > > 
> > > 魔改是因为有部分皮肤文件失效，加载到这些皮肤的时候会崩溃，我用的五月份的魔改，在船坞里找到荒潮和满朝这两艘船时就会闪退，我把这两个的皮肤原文件替换回来后就正常了，现在的不清楚
> > 
> > 
> > 你五月份的魔改包出处还记得在哪里吗，可以分享一下嘛，当然如果找不到了也没关系。
> 
> https://laowang.vip/home.php?mod=space&uid=1247954&do=thread&view=me&from=space 这个作者一直在整理

这个点开要登陆，看链接还是需要开vip的样子，不过还是谢啦

**Comment by Harmskyblue** [comment]
> 解决闪退问请转向使用 https://github.com/JMBQ/azurlane/releases/tag/1.0 ，注意配置文件名，感谢Rem。

看了一个小时，不是很懂该怎么使用这个release的文件，是复制到碧蓝安装包apk里的lib路径下替换掉吗，我试着解压出来替换后重新压缩成apk，显示安装包解析失败。

**Comment by kwanKC** [comment]
> > 解决闪退问请转向使用 https://github.com/JMBQ/azurlane/releases/tag/1.0 ，注意配置文件名，感谢Rem。
> 
> 看了一个小时，不是很懂该怎么使用这个release的文件，是复制到碧蓝安装包apk里的lib路径下替换掉吗，我试着解压出来替换后重新压缩成apk，显示安装包解析失败。

不是这么用的，这个链接的仓库里只有个readme，包在release里，看patch_perseus.sh脚本这三个文件应该要在build之前放进去。我的理解是改patch_perseus.sh脚本里43行的代码，把Perseus的仓库里的文件换成JMBQ的，再改下面两条sed语句。
~~不过不太懂咋再github上搞，apk的build也不会，不知道有没有大神指点一下~~
试着fork了这个repository来改，把几个库跟配置文件都改成了JMBQ的，但还是不行，甚至连enjoy the feet都看不到了XD

**Comment by otakumr** [comment]
折腾了很久，终于是可以同时用魔改安装包加魔改皮肤了。没有太多花里胡哨的，下一个逍遥模拟器，然后安装这个仓库里的release文件，闪退就多打开几次。第一次进入游戏先选择下载全部的文件，下载完成后用mt管理器把要替换的文件（我用的9月的魔改文件）都替换掉，再次进入游戏就完成了
